spring.application.name=simulacaoserasa
spring.data.mongodb.uri=mongodb+srv://raquelbmrs:9ybXq78ciLgo5rru@dindin-aws-sp.ebbbs.mongodb.net/db_simulacaoSerasa
spring.data.mongodb.database=db_simulacaoSerasa